-- =============================================================================
-- Plataforma de Gestión de Proyectos FCI - Universidad de Guayaquil
-- Script de autenticación: roles, perfiles, políticas RLS y trigger.
-- Aplica este script en Supabase (SQL Editor) ANTES de usar el login.
-- =============================================================================

-- 1. Tipo ENUM para roles
DO $$ BEGIN
  CREATE TYPE public.tipo_rol AS ENUM (
    'administradora', 'investigadora', 'formadora', 'mujer_emprendedora', 'institucion_aliada'
  );
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- 2. Tabla de ROLES (CORREGIDA)
--    id  -> PK autoincremental
--    id_usuario -> FK a auth.users
CREATE TABLE IF NOT EXISTS public.roles_usuario (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario       UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  rol              public.tipo_rol NOT NULL,
  fecha_asignacion TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  UNIQUE (id_usuario, rol)
);

-- 3. Tabla de PERFILES (versión completa)
CREATE TABLE IF NOT EXISTS public.perfiles_usuario (
  id                      UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  nombre_completo         TEXT,
  email                   TEXT,
  telefono                TEXT,
  breve_descripcion       TEXT,
  linkedin                TEXT,
  fecha_registro          TIMESTAMP WITH TIME ZONE DEFAULT now(),
  fecha_actualizacion     TIMESTAMP WITH TIME ZONE DEFAULT now(),
  ultimo_acceso           TIMESTAMP WITH TIME ZONE,
  avatar_url              TEXT,
  notificaciones_activas  BOOLEAN DEFAULT TRUE,
  cuenta_activa           BOOLEAN DEFAULT TRUE
);

-- 4. Habilitar Row Level Security
ALTER TABLE public.roles_usuario   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.perfiles_usuario ENABLE ROW LEVEL SECURITY;

-- 5. POLÍTICAS RLS (sin esto, nadie puede leer/escribir sus datos)
-- Perfiles: cada usuario gestiona su propio perfil
DROP POLICY IF EXISTS "perfiles_select_propio" ON public.perfiles_usuario;
CREATE POLICY "perfiles_select_propio" ON public.perfiles_usuario
  FOR SELECT
  USING (id = auth.uid());

DROP POLICY IF EXISTS "perfiles_insert_propio" ON public.perfiles_usuario;
CREATE POLICY "perfiles_insert_propio" ON public.perfiles_usuario
  FOR INSERT
  WITH CHECK (id = auth.uid());

DROP POLICY IF EXISTS "perfiles_update_propio" ON public.perfiles_usuario;
CREATE POLICY "perfiles_update_propio" ON public.perfiles_usuario
  FOR UPDATE
  USING (id = auth.uid())
  WITH CHECK (id = auth.uid());

-- Roles: cada usuario puede leer su propio rol
DROP POLICY IF EXISTS "roles_select_propio" ON public.roles_usuario;
CREATE POLICY "roles_select_propio" ON public.roles_usuario
  FOR SELECT
  USING (id_usuario = auth.uid());

-- 6. Trigger: crear perfil automáticamente al registrarse
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.perfiles_usuario (id, nombre_completo, email)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data ->> 'nombre_completo', NULL),
    NEW.email
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();
